# Site settings
title: Derik Ng
email: derikn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a personal website of Derik Ng.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.derikng.com" # the base hostname & protocol for your site
twitter_username: drkng 
github_username: derikn

# Build settings
markdown: kramdown
